trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '904233121797'  # <-- Replace with your real account ID

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g aws-cdk
      npm install
      npm run build
    displayName: 'Install dependencies and build CDK app'

  # ✅ Optional: Just verify the service connection works
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'
      regionName: '$(AWS_REGION)'
      awsCommand: 'sts'
      awsSubCommand: 'get-caller-identity'
    displayName: 'Verify AWS credentials'

  # ✅ Deploy CDK app using same service connection (no need for exported vars)
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'
      regionName: '$(AWS_REGION)'
      awsCommand: 'shell'
      awsSubCommand: |
        cdk deploy --require-approval never
    displayName: 'Deploy CDK stack'






