trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '904233121797'  # Replace with your actual AWS account ID

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g aws-cdk
      npm install
      npm run build
    displayName: 'Install dependencies and build CDK app'

  # ✅ Use this task to verify service connection AND run cdk deploy inside it
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'  # Your service connection name
      regionName: '$(AWS_REGION)'
      awsCommand: 'custom'
      awsSubCommand: |
        npm install -g aws-cdk
        npm install
        npm run build
        cdk deploy --require-approval never
    displayName: 'Deploy CDK stack using AWS service connection'







