trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '904233121797'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install project dependencies'

  # ✅ Everything runs here while AWS creds are valid
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'  # <- your service connection
      regionName: '$(AWS_REGION)'
      awsCommand: 's3'  # Required field, but not actually used
      awsSubCommand: 'ls'  # Required field, but not actually used
      scriptType: 'bash'
      script: |
        echo "Deploying CDK..."
        npm install -g aws-cdk
        npm run build
        cdk deploy --require-approval never
    displayName: 'CDK Deploy (with AWS creds from service connection)'









