trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '9042331217972'  # <-- Replace with your actual AWS Account ID

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g aws-cdk
      npm install
      npm run build
    displayName: 'Install dependencies and build CDK app'

  # This uses the ADO AWS service connection (aws-dev) to inject credentials
  # No need to set AWS creds manually if you're using this properly.
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'  # Ensure this is set up in ADO with proper permissions
      regionName: '$(AWS_REGION)'
      awsCommand: 'sts'
      awsSubCommand: 'get-caller-identity'
    displayName: 'Verify AWS credentials'

  - script: |
      cdk deploy --require-approval never
    displayName: 'Deploy CDK stack'
    env:
      AWS_REGION: $(AWS_REGION)
      AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)  # Passed to CDK stack’s env block



