trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g aws-cdk
      npm install
      npm run build
    displayName: 'Install dependencies and build CDK app'

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-dev'  # Name of your AWS Service Connection
      regionName: 'us-east-1'  # Replace with your desired AWS region
      command: 'sts'
      arguments: 'get-caller-identity'  # This command verifies AWS credentials
    displayName: 'Test AWS CLI Authentication'

  - script: |
      cdk deploy --require-approval never
    displayName: 'Deploy CDK stack'
