trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '904233121797'  # Replace with your real account ID

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g aws-cdk
      npm install
      npm run build
    displayName: 'Install dependencies and build CDK app'

  # ✅ Verifies and injects AWS credentials using your service connection
  - task: AWSCLI@1
    name: InjectCreds
    inputs:
      awsCredentials: 'aws-dev'  # your service connection
      regionName: '$(AWS_REGION)'
      awsCommand: 'sts'
      awsSubCommand: 'get-caller-identity'
    displayName: 'Verify AWS credentials'

  # ✅ Deploys CDK app using credentials injected by AWSCLI@1
  - bash: |
      npm install -g aws-cdk
      npm install
      npm run build
      cdk deploy --require-approval never
    displayName: 'Deploy CDK stack'
    env:
      AWS_ACCESS_KEY_ID: $(InjectCreds.AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(InjectCreds.AWS_SECRET_ACCESS_KEY)
      AWS_SESSION_TOKEN: $(InjectCreds.AWS_SESSION_TOKEN)
      AWS_REGION: $(AWS_REGION)
      AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)








